name: Keep Alive

on:
  schedule:
    - cron: '0 9 1 * *'  # Spustí se 1. každého měsíce v 9:00
  workflow_dispatch:      # Možnost spustit ručně kdykoliv

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Keep alive
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit --allow-empty -m "Keep alive - $(date +'%Y-%m')"
          git push
